### ISSUE TITLE
Instalación de Anaconda, Python, R y GitHub. 

### ISSUE THREAD

**Issue by alexanderquispe** [d2cml-ai/CausalAI-Course#2]
Estimado Estudiantes,

Muchas gracias por haber elegido el curso Inferencia Causal y Machine learning, espero que durante el semestre todos podamos aprovechar al máximo tanto las clases como los labs para aprender juntos.

Quería dejar una lista de pasos que deben de seguir para tener todas las herramientas listas para nuestra primera semana.

1. Instalación de Anaconda. Anaconda es una especie de administrador de paquetes(programas) que nos va a simplificar la vida un montón en la instalación de Python, R y Jupyter Notebook. Si alguno de ustedes tiene instalado Python previamente, les recomendaria que borren o desinstalen esos archivos, para poder setear todo desde Anaconda.
2. Acá les dejo el [link ](https://www.youtube.com/watch?v=BGTor-HJvKA)para que vean cómo setear Anaconda. Una vez instalado Anaconda tanto Jupyter Notebook como Python vienen instalados por dafault, así que no tienen que hacer pasos extras para añadirlos.
3. Instalar GiHub Desktop y crear cuenta. Necesito que instalen GitHub que es como un canalizador de códigos de Git, para el manejo de control version de todos los archivos que ustedes y yo subirermos y/o modificaremos. En este [video ](https://www.youtube.com/watch?v=3JdDAJ2YPeU)verán cómo instalar GitHub Desktop. Solo necesitan entrar a la pagina de Github para crearse su cuenta y necesito que me envíen su nombre de usuario para poder agregarlos al repositorio.
4. En el Banco Mundial se utiliza este [video ](https://mfr.osf.io/render?url=https://osf.io/8h6eb/?direct%26mode=render%26action=download%26mode=render)para introducir a los nuevos investigadores en GitHub. Recomiendo encarecidamente que vean el video, sobre el cual se basará la primera semana de clases.

**Instalar Visual Code**

Revisen este [link ](https://www.youtube.com/watch?v=CPmQwlycfGI)para que vean cómo descargar y manejar visual code. No necesariamente tienen que instalarlo desde anaconda, pueden hacerlo de manera independiente.

**Markdown**

Acá también les adjunto un [video](https://www.youtube.com/watch?v=pTCROLZLhDM) de cómo usar Markdown en VisualCode, me parece muy bueno y pedagógico.

**Comment by alexanderquispe** [comment]
4. **Instalar Visual Code (Depende de ustedes pueden usar tambien sublime o Notepad++)**
Revisen este [link](https://www.youtube.com/watch?v=MlIzFUI1QGA) para que vean cómo descargar y manejar visual code. No necesariamente tienen que instalarlo desde anaconda, pueden hacerlo de manera independiente. 

5. **Markdown**
Acá también les adjunto un [video](https://www.youtube.com/watch?v=pTCROLZLhDM) de cómo usar Markdown en VisualCode, me parece muy bueno y pedagógico.

**Comment by ecirilomendoza** [comment]
Given the installation problems that some of us have had, we have prepared a guide to install Python and R in Jupyter Notebook. Its is in the "Installation" folder of this course.
Check this [file](https://github.com/alexanderquispe/ECO224/blob/main/Installation/Python_R_installation.md).
