### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ecirilomendoza** [d2cml-ai/CausalAI-Course#21]
Given the installation problems that some of us have had, we have prepared a guide to install Python and R in Jupyter Notebook. Its is in the "Installation" folder of this course.

**Comment by SandraMartinezGutierrez** [comment]
As there were some problems about establishing the connection between R and Jupyter Notebook, here there is a new guide that would help.  
* https://stackoverflow.com/questions/38387027/unable-to-load-irkernel-in-jupyter-notebook

Notice that it is essential to have installed Git previously, so click here https://git-scm.com/download/win and select the executable that fixes better to your operating system.
